# Generated by Django 2.1.2 on 2018-11-24 00:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=35)),
                ('model', models.CharField(max_length=75)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=65)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.CharField(max_length=150)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trax.Car')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trax.User'),
        ),
    ]
