# Generated by Django 2.1.2 on 2018-11-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
