# Generated by Django 2.1.2 on 2018-11-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0002_auto_20181124_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
