# Generated by Django 2.1.2 on 2018-11-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0004_auto_20181126_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user',
            new_name='name',
        ),
    ]
