# Generated by Django 2.1.2 on 2018-11-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0005_auto_20181126_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
