# Generated by Django 2.1.2 on 2018-11-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0006_car_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
    ]
