# Generated by Django 2.1.2 on 2018-11-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0007_remove_car_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.CharField(max_length=75),
        ),
    ]
