# Generated by Django 2.1.2 on 2018-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trax', '0008_auto_20181127_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
